Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm8250/OnePlus8T/HiFi.conf"
	Comment "HiFi quality Music."
}

Include.rxinit.File "/codecs/qcom-lpass/rx-macro/init.conf"
Include.wcdinit.File "/codecs/wcd938x/init.conf"
